name: Shaker CI

# Exécute ce workflow sur chaque commit ou pull request sur la branche 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Vérifie le code depuis le dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuration de Python (si ton projet utilise Python)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Installation des dépendances depuis un fichier requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Exécuter des tests (si tu as des tests, par exemple avec pytest)
    - name: Run tests
      run: |
        if [ -f tests/test_shaker.py ]; then pytest tests/test_shaker.py; fi
